export const foodTypes = {
    FOOD_GET: 'FOOD_GET',
    FOOD_ADD: 'FOOD_ADD',
    FOOD_FILTERED: 'FOOD_FILTERED',
    FOOD_DELETE: 'FOOD_DELETE'
}

export const restaurantTypes = {
    RESTAURANT_GET: 'RESTAURANT_GET',
    RESTAURANT_ADD: 'RESTAURANT_ADD',
    RESTAURANT_FILTERED: 'RESTAURANT_FILTERED',
    RESTAURANT_DELETE: 'RESTAURANT_DELETE'
}

export const orderTypes = {
    ORDER_ADD: 'ORDER_ADD',
    ORDER_GET: 'ORDER_GET'
}
